# data prep config ------------------------------------------------------------
random_seed: 42
segment_prefix: "segment"
gt_ext: "gt" # no dots
pos_ext: "pos"
file_segment_delimiter: "."
seg_offset: -2 # position in filename after splitting by delimiter
num_pairings: 5 # n pairings for each sample from each subpopulation
samples_list: "/scratch/Shares/layer/projects/gt_similarity_search/sample_list.txt"
sample_table: "/scratch/Shares/layer/projects/gt_similarity_search/1kg_sample_table.tsv"
segments_dir: "/scratch/Shares/layer/projects/gt_similarity_search/segments"
outdir: "/scratch/Shares/layer/projects/gt_similarity_search/reviews_data"

model_config: "conv1d_config.yaml"
model_prefix: "reviews"

container: "/scratch/Shares/layer/containers/genosis.sif"
