executor: slurm
latency-wait: 5
default-resources:
  slurm_partition: "short"
  runtime: 240 # minutes
  mem: 32G
  nodes: 1
  cpus_per_task: 1

set-resources:
  TrainModel:
    slurm_partition: "nvidia-a100"
    runtime: 10080 # 1 week
    mem: 32G
    nodes: 1
    cpus_per_task: 16
    slurm_extra: f"--gres=gpu:1"
