executor: slurm
latency-wait: 5
default-resources:
  slurm_partition: "short"
  runtime: 120 # minutes
  mem: 32G
  nodes: 1
  cpus_per_task: 1

set-resources:
  TrainModel:
    slurm_partition: "nvidia-a100"
    runtime: 1440 # 24 hours
    mem: 128G
    nodes: 1
    cpus_per_task: 32
    slurm_extra: f"--gres=gpu:1"
